#!/usr/bin/env bash
set -e

echo ""
echo "====================================================="
echo "  TCS Financial Forecasting Agent - Setup Script"
echo "====================================================="
echo ""

# ── Check Docker is installed ─────────────────────────────────────────────────
if ! command -v docker &> /dev/null; then
    echo "[ERROR] Docker is not installed."
    echo ""
    echo "Please install Docker Desktop from:"
    echo "  https://www.docker.com/products/docker-desktop"
    echo ""
    echo "After installing, re-run this script."
    exit 1
fi

# ── Check Docker daemon is running ────────────────────────────────────────────
if ! docker info &> /dev/null; then
    echo "[ERROR] Docker is not running."
    echo ""
    echo "Please start Docker Desktop and wait for it to fully load,"
    echo "then re-run this script."
    exit 1
fi

echo "[OK] Docker is running."
echo ""

# ── Check if .env already exists ──────────────────────────────────────────────
if [ -f ".env" ]; then
    echo "[INFO] .env file already exists. Skipping key prompt."
    echo "       To change your API key, edit .env and re-run setup.sh."
    echo ""
else
    # ── Prompt for Gemini API key ──────────────────────────────────────────────
    echo "You need a FREE Google Gemini API key."
    echo "Get one at: https://aistudio.google.com/app/apikey"
    echo ""
    read -p "Paste your Gemini API key here and press Enter: " GOOGLE_API_KEY

    if [ -z "$GOOGLE_API_KEY" ]; then
        echo "[ERROR] No API key entered. Exiting."
        exit 1
    fi

    # ── Write .env file ────────────────────────────────────────────────────────
    cat > .env << ENV
# Auto-generated by setup.sh
GOOGLE_API_KEY=${GOOGLE_API_KEY}
GOOGLE_MODEL=gemini-flash-latest

MYSQL_HOST=localhost
MYSQL_PORT=3306
MYSQL_USER=root
MYSQL_PASSWORD=tcsagent2024
MYSQL_DB=tcs_forecast

CHROMA_PERSIST_DIR=./chroma_db
CHROMA_COLLECTION=tcs_documents
DOC_CACHE_DIR=./doc_cache
ENV

    echo ""
    echo "[OK] .env file created."
    echo ""
fi

# ── Build and start with Docker Compose ──────────────────────────────────────
echo "Starting the application with Docker Compose..."
echo "This will take 3-5 minutes on first run (downloading images + installing packages)."
echo ""

docker compose up --build -d

echo ""
echo "====================================================="
echo "  Setup complete!"
echo "====================================================="
echo ""
echo "  API:       http://localhost:8000"
echo "  Swagger:   http://localhost:8000/docs"
echo "  Health:    http://localhost:8000/health/capabilities"
echo ""
echo "  The first forecast request will take 2-3 minutes"
echo "  (downloads TCS financial PDFs and indexes them)."
echo "  Subsequent requests are instant."
echo ""
echo "  To stop:      docker compose down"
echo "  To view logs: docker compose logs -f"
echo ""
