@echo off
setlocal enabledelayedexpansion

echo.
echo =====================================================
echo   TCS Financial Forecasting Agent - Setup Script
echo =====================================================
echo.

:: ── Check Docker is installed ────────────────────────────────────────────────
where docker >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Docker is not installed.
    echo.
    echo Please install Docker Desktop from:
    echo   https://www.docker.com/products/docker-desktop
    echo.
    echo After installing, re-run this script.
    pause
    exit /b 1
)

:: ── Check Docker daemon is running ───────────────────────────────────────────
docker info >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Docker Desktop is not running.
    echo.
    echo Please open Docker Desktop, wait for it to start
    echo (look for "Engine running" in the bottom left),
    echo then re-run this script.
    pause
    exit /b 1
)

echo [OK] Docker is running.
echo.

:: ── Check if .env already exists ─────────────────────────────────────────────
if exist .env (
    echo [INFO] .env file already exists. Skipping key prompt.
    echo        To change your API key, edit .env and re-run setup.bat.
    echo.
    goto :compose
)

:: ── Prompt for Gemini API key ────────────────────────────────────────────────
echo You need a FREE Google Gemini API key.
echo Get one at: https://aistudio.google.com/app/apikey
echo.
set /p GOOGLE_API_KEY="Paste your Gemini API key here and press Enter: "

if "!GOOGLE_API_KEY!"=="" (
    echo [ERROR] No API key entered. Exiting.
    pause
    exit /b 1
)

:: ── Write .env file ──────────────────────────────────────────────────────────
(
echo # Auto-generated by setup.bat
echo GOOGLE_API_KEY=!GOOGLE_API_KEY!
echo GOOGLE_MODEL=gemini-flash-latest
echo.
echo MYSQL_HOST=localhost
echo MYSQL_PORT=3306
echo MYSQL_USER=root
echo MYSQL_PASSWORD=tcsagent2024
echo MYSQL_DB=tcs_forecast
echo.
echo CHROMA_PERSIST_DIR=./chroma_db
echo CHROMA_COLLECTION=tcs_documents
echo DOC_CACHE_DIR=./doc_cache
) > .env

echo.
echo [OK] .env file created.
echo.

:: ── Build and start with Docker Compose ──────────────────────────────────────
:compose
echo Starting the application with Docker Compose...
echo This will take 3-5 minutes on first run (downloading images + installing packages).
echo.

docker compose up --build -d

if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Docker Compose failed. Check the error above.
    pause
    exit /b 1
)

echo.
echo =====================================================
echo   Setup complete!
echo =====================================================
echo.
echo   API:       http://localhost:8000
echo   Swagger:   http://localhost:8000/docs
echo   Health:    http://localhost:8000/health/capabilities
echo.
echo   The first forecast request will take 2-3 minutes
echo   (downloads TCS financial PDFs and indexes them).
echo   Subsequent requests are instant.
echo.
echo   To stop:   docker compose down
echo   To view logs: docker compose logs -f
echo.
pause
